### ISSUE TITLE
To field is required

### ISSUE THREAD

**Issue by Bilonik** [smaho-engineering/mailto#4]
to != null && to.isNotEmpty && to.every((t) => t.isNotEmpty)
"Destination email address \"to\" is a required parameter and all addresses must not be empty."

**Comment by vincevargadev** [comment]
Hi @alonhh. Thank you for your feedback. Why do you think the "to" field should not be required?

**Comment by vincevargadev** [comment]
You can bypass the validation in `0.2.0` https://pub.dev/packages/mailto#skip-validation However, I'm not sure what's going to happen if you do.

**Comment by monsieurtanuki** [comment]
@vargavince91 `to:` does not seem to be mandatory in https://tools.ietf.org/html/rfc6068

A use-case is: "Do you like this app? Share it with your friends!" that opens a new mail with a subject and a body, but no recipients (to be filled by the user of course).

Maybe the validation parameters could be more fine grained, like adding an explicit flag "I know it may sound strange but I don't populate the `to:` field". Or just altogether accept the possibility of `to` being empty or null.

**Comment by vincevargadev** [comment]
Thanks for the comment @monsieurtanuki. Your example does make sense, indeed. I'm going to check if the majority of the email clients can handle missing to fields, and if they can, I'm going to remove most validation and let it be the user's responsibility to pass in useful information to the library.
