### ISSUE TITLE
Migrate to nullsafety

### ISSUE THREAD

**Issue by Wikiwix** [smaho-engineering/mailto#7]
All the dependencies are already migrated, so a migration to null safety would be great.

**Comment by vincevargadev** [comment]
The null safe version of the package is available as `mailto: ^2.0.0-nullsafety.0`

See: https://pub.dev/packages/mailto/versions/2.0.0-nullsafety.0

Feedback is welcome, if something's off with the migration, please open an issue or, even better, a PR with the fix.

@Wikiwix could you check if the migrated version is correct and works for you? Thanks
