### ISSUE TITLE
Question:  Add Attachment

### ISSUE THREAD

**Issue by rlfolden** [smaho-engineering/mailto#9]
Is there a way to add an attachment?  I want to launch the MacOS email client and fill in the To;, etc., fields but also add a PDF attachment.

**Comment by vincevargadev** [comment]
This is not possible because we are limited by what the mailto is designed for. For more info, check out this question on StackOverflow: [using mailto to send email with an attachment](https://stackoverflow.com/questions/5233556/using-mailto-to-send-email-with-an-attachment)

**Comment by Aruljebaraj** [comment]
any update on this??
